dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"
os:
  - linux
env:
  - USIM_WAITQUEUE="" DEBUG="-O"
  - USIM_WAITQUEUE=""
  - USIM_WAITQUEUE="SD"
before_script:
  - python -m pip install pip --upgrade
  - python -m pip list
  - export PYTHONHASHSEED=${PYTHONHASHSEED:-${RANDOM}}
  - echo "export PYTHONHASHSEED=${PYTHONHASHSEED}"
  - pip install .[test]
  - pip install codecov
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
  - export PYTEST_ADDOPTS=-v
script:
  - python -m flake8
  - python $DEBUG -m coverage run -m pytest
after_success:
  - coverage report && codecov
